feat(pipeline) : Use CD35 ArcGis API
gip-inclusion/data-inclusion pull request #233
Opened 2024-05-07 15:50 UTC by vperron

... and fix some pipeline requirement issues.

2024-05-13 13:27 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +        from furl import furl
ok du coup je ne suis pas favorable à ces imports en top level. Je pense que, contrairement au task airflow, ça n'est pas réellement nécessaire et qu'on devrait faire ce qui est fait normalement ;)

2024-05-13 13:49 UTC, vmttn requested changes
ok :+1: est-ce qu'on en profite pour tester quelques champs dans le model staging ?

2024-05-13 13:49 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +            f"{self.base_url}?where=1=1&returnCountOnly=true&f=json"
nit : quitte à importer `furl` on pourrait l'utiliser là

2024-05-13 13:49 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +        from furl import furl
ok du coup je ne suis pas favorable à ces imports. Je pense que, contrairement aux tasks airflow, ça n'est pas nécessaire et qu'on devrait donc faire ce qui est fait normalement ;)

2024-05-13 13:49 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +        response.raise_for_status()
c'est déjà fait dans BaseApiClient !

2024-05-13 13:49 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +            response = self.session.get(next_url)
idem, est déjà fait dans BaseApiClient

2024-05-13 13:49 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +            params["where"] = f"(ID >= {i} AND ID < {i+ARCGIS_MAX_PAGE_SIZE})"
pourquoi ne pas utiliser le query param `resultOffset` ? rien ne garantit que les `ID` existent tous de 1 à <count>. Il se peut que le compteur s'incrémente et que certaines lignes soient supprimées.

2024-05-13 14:28 UTC, vperron commented on pipeline/dags/dag_utils/sources/cd35.py
> +            f"{self.base_url}?where=1=1&returnCountOnly=true&f=json"
je trouvais ça assez explicite comme ça sans ajouter d'appel Python, mais pourquoi pas.

2024-05-13 14:29 UTC, vperron commented on pipeline/dags/dag_utils/sources/cd35.py
> +        from furl import furl
Alors si je ne le mets pas là, j'ai le webserver Airflow qui crashe au parsing parce que il ne connait pas `furl`.

Actuellement `import_sources` va lire chaque module importé de `dag_utils.sources`. Si ces modules (`cd35.py` par exemple) importent une lib inconnue du webserver Airflow, kaboom.

2024-05-13 14:33 UTC, vperron commented on pipeline/dags/dag_utils/sources/cd35.py
> +            params["where"] = f"(ID >= {i} AND ID < {i+ARCGIS_MAX_PAGE_SIZE})"
En effet. J'ai été un peu  optimiste.

2024-05-13 14:33 UTC, vperron commented on pipeline/dags/dag_utils/sources/cd35.py
> +            params["where"] = f"(ID >= {i} AND ID < {i+ARCGIS_MAX_PAGE_SIZE})"
(mais c'etait le cas pour l'instant)

2024-05-14 07:28 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +        from furl import furl
:exploding_head: ah oui mais je n'avais pas vu passée cette dépendance

2024-05-14 07:58 UTC, vmttn commented on pipeline/dags/dag_utils/sources/cd35.py
> +        from furl import furl
ok on changera dans un 2eme temps

2024-05-14 12:30 UTC, vmttn approved these changes

2024-05-14 12:48 UTC, merged