wip
gip-inclusion/data-inclusion pull request #257
Opened 2024-07-11 16:06 UTC by hlecuyer

2024-07-12 10:52 UTC, vmttn reviewed
Cool ! Quelques commentaires plutot sur le code, je n'ai pas encore checké plus en détail

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +),
une autre façon de procéder (peut-être un poil plus lisible et sans `LATERAL`, donc moins complexe)

```suggestion
        ('transport', 'mobilite--comprendre-et-utiliser-les-transports-en-commun'),
        ('transport', 'mobilite--etre-accompagne-dans-son-parcours-mobilite'),
        ('vêtements', 'equipement-et-alimentation--habillement'),
        ('vih', 'sante--vie-relationnelle-et-affective')
    ) AS x (category, thematique)
),
```

en gros on duplique des category
et du coup ça donne un simple JOIN+GROUP BY plus bas :

```sql
thematiques AS (
    SELECT
        categories.structure_id,
        ARRAY_AGG(DISTINCT thematique) AS thematiques
    FROM categories
    LEFT JOIN di_thematiques_by_fredo_categories ON categories.value = di_thematiques_by_fredo_categories.category
    GROUP BY categories.structure_id
),
```

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +di_thematiques_by_fredo_categories AS (
ok pour créer un model annexe au même niveau pour stocker ce mapping. J'aimais bien ton idée de les rendre privés avec un underscore.

Pour les autres mappings, j'ai l'impression que ça rajouterait pas mal de petits fichiers (et donc + d'indirections et de clics), je te laisse juge

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        -- Mapping: https://www.notion.so/dora-beta/8c8d883758df47649902ddba55ab2236?v=56c7542b590c42febc79db8d3ffe9f81&p=84e6e41b6a3b4f54bee46e11aa41ff47&pm=s
pratique :+1:

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +di_nom_and_types_by_fredo_services AS (
Plutot d'avis de ne garder que la partie `di_types_by_fredo_services`.

Pour le `nom`, il suffit de capitaliser et de remplacer ` / ` par ` et `, ce qui aura l'avantage de réduire l'adhérence aux valeurs possibles

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        NULL::text []                                                                         AS "modes_accueil",
Utilise `CAST( ... AS ... )` au lieu de `::`.

La raison :
Les macros dbt et dbt_utils utilisent `CAST(... AS ...)` (qui est du sql standard) et pas `::` (qui est du sql postgresql), car dbt pas spécifique à pg bien sur.
Or il y a une regle sqlfluff pour harmoniser les cast (ça pete si les 2 styles sont utilisés dans le m model, macros comprises). Je trouve que la regle n'est pas absurbe.

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        ARRAY_AGG(DISTINCT thematique) AS thematiques -- noqa: RF02
bizarre que tu aies besoin de ce noqa :shrug: 
le commentaire plus haut sur le fait de simplifier le mapping des thématiques fixerait ça sans avoir à creuser davantage ;)

2024-07-12 10:52 UTC, vmttn commented on pipeline/dbt/models/staging/sources/fredo/_fredo__models.yml
> +      - name: structure_id
nickel :+1:

2024-07-15 07:42 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +di_thematiques_by_fredo_categories AS (
d'accord avec toi pour les petits mapping.

2024-07-15 12:22 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +),
je pense que c'est mieux sans LATERAL, voir même en lisibilité, mais c'est surement + subjectif

si tu veux, dans le fichier séparé, t'as aussi l'option d'utiliser un format json (cf par exemple ce qui est fait https://github.com/gip-inclusion/data-inclusion/blob/main/pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__categories.sql)

2024-07-15 12:44 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +),
Pas sur que le json accete des keys identique au sein d'un meme objet. Je vais rester en sql je pense. Ok pour enlever le lateral :)

2024-07-15 13:39 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        ARRAY_AGG(DISTINCT thematique) AS thematiques -- noqa: RF02
Pas sur j'avais le meme un peu plus haut, et j'ai pas reussi a le passer non plus. On poura regarder ensemble si tu veux

2024-07-15 14:10 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        ARRAY_AGG(DISTINCT thematique) AS thematiques -- noqa: RF02
a ba si je vais faire la meme
ok pour moi

2024-07-15 14:26 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +),
pardon je n'ai pas été très clair : tu peux formatter en json si tu veux garder le format clé -> array pour la lisibilité du mapping (ou juste avec du SQL bien formatté sans json), du moment que tu gardes le format de sortie du model qui permet de se passer de lateral bien entendu

2024-07-16 07:15 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +),
non mais ca me va comme ca (+ un peu la flemme de le faire une troisieme fois il y a quand meme pas mal de lignes)

2024-07-16 09:32 UTC, vmttn requested changes
encore quelques petits détails, mais c'est propre :+1:

2024-07-16 09:32 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +            SELECT REPLACE((UPPER(SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo, 1, 1)) || SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo, 2)), '/', 'et')
nit

```suggestion
            SELECT UPPER(LEFT(di_nom_and_types_by_fredo_services.service_fredo, 1)) || SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo FROM 2)), '/', 'et')
```

2024-07-16 09:32 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +    LEFT JOIN mode_orient_benef ON structures.id = mode_orient_benef.structure_id
nit

mentalement j'aurais plutot fait dans ce sens, pour s'assurer qu'on a bien la bonne quantité d'éléments. Ca joue des tours parfois, cela dit ça n'a pas d'impact ici !

```suggestion
    FROM services
    LEFT JOIN structures ON services.structure_id = structures.id
    LEFT JOIN thematiques ON structures.id = thematiques.structure_id
    LEFT JOIN profils ON structures.id = profils.structure_id
    LEFT JOIN frais ON structures.id = frais.structure_id
    LEFT JOIN frais_autres ON structures.id = frais_autres.structure_id
    LEFT JOIN mode_orient_benef ON structures.id = mode_orient_benef.structure_id
```

2024-07-16 09:32 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        CAST(NULL AS DATE)                                                                    AS "date_maj",
finalement qu'est-ce qu'on a décidé pour la date de maj ? tu as vu avec Antoine ?
pour moi, plusieurs possibilité : 
* soit l'information existe chez eux, mais ils ne l'ont pas partagé et on peut leur demander
* soit l'information n'existe pas (peu probable), et dans ce cas soit on hardcode et on réfléchit de nouveau à la pertinence du caractère obligatoire de ce champ :sweat_smile:

2024-07-16 09:32 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__structures.sql
> +        CAST('2025-07-11' AS DATE)     AS "date_maj",
cf le commentaire sur le `date_maj` côté services

2024-07-16 09:32 UTC, vmttn commented on pipeline/pyproject.toml
> +large_file_skip_byte_limit = 25000
toujours nécessaire ?

2024-07-16 09:32 UTC, vmttn commented on pipeline/scripts/update_schema_seeds.py
> +    "https://raw.githubusercontent.com/gip-inclusion/data-inclusion-schema/v0.15.0_fredo/schemas/extra/",  # noqa: E501
à retirer

2024-07-17 09:35 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +    SELECT
J'ai desactive l'ordre des colonnes par complexite du coup mais pourquoi le premier lien ? https://docs.sqlfluff.com/en/stable/rules.html#ignoring-line-ranges

2024-07-17 09:44 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +            SELECT REPLACE((UPPER(SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo, 1, 1)) || SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo, 2)), '/', 'et')
il manque le replace ici non ?

2024-07-17 09:46 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +            SELECT REPLACE((UPPER(SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo, 1, 1)) || SUBSTRING(di_nom_and_types_by_fredo_services.service_fredo, 2)), '/', 'et')
Ok pour LEFT et FROM int

2024-07-17 09:50 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        CAST(NULL AS DATE)                                                                    AS "date_maj",
pour le moment je l'ai hard code j'attend un retour d'Antoine

2024-07-18 13:24 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +    SELECT
en fait j'hésitais sur le fait de désactiver cette régle au global ou de la désactiver sur des blocs de manière ad hoc

donc fine by me

2024-07-18 13:30 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/fredo/int_fredo__services.sql
> +        structures.commune                                                                    AS "code_postal",
bien vu il fallait en fait supprimer la ligne !

2024-07-18 13:32 UTC, vmttn reviewed
lgtm ! on passe en ready for review et on regarde ce que ça donne en staging et sur la preprod dora ?

2024-07-18 14:35 UTC, vmttn commented on pipeline/dbt/models/staging/sources/fredo/stg_fredo__structures.sql
> +        NULLIF(TRIM(data ->> 'last_update'), '')              AS "last_update",
tu peux nettoyer le champ en staging

```suggestion
        CAST(NULLIF(TRIM(data ->> 'last_update'), '') AS DATE)              AS "last_update",
```

voir même utiliser TO_DATE

2024-08-28 08:30 UTC, merged