feat(pipeline) : Lancer et snapshotter le modèle de monotoring
gip-inclusion/data-inclusion pull request #267
Opened 2024-08-06 09:22 UTC by vperron

Tout est dans le titre :)

2024-08-06 11:18 UTC, vperron commented
@vmttn je me demande si:
- je ne devrais pas merger celle-ci __avant__ celle sur le geocodage #266 
- au passage y mettre un score supplémentaire sur le nombre de lignes de marts avec un score supérieur à 0.8 ? ou autre ?

Ca permettra de voir l'évolution, sachant que la première sera trompeuse: aujourd'hui on a beaucoup de scores au-delà de 0.8 pour des matchs foncièrement erronés (cf commentaire du second commit de cette PR)

2024-08-09 10:41 UTC, vmttn requested changes

2024-08-09 10:41 UTC, vmttn commented on pipeline/dags/import_data_inclusion_api.py
> +    generate_source_stats = dbt_operator_factory(
```suggestion
    build_source_stats = dbt_operator_factory(
```

2024-08-09 10:41 UTC, vmttn commented on pipeline/dbt/snapshots/quality/snps_quality__stats.sql
> +      unique_key="source||'-'||stream",
```suggestion
      unique_key="source||'--'||stream",
```

2024-08-09 10:41 UTC, vmttn commented on pipeline/dbt/snapshots/quality/snps_quality__stats.sql
> +        source || '-' || stream AS id,
```suggestion
        source || '--' || stream AS id,
```

2024-08-09 10:41 UTC, vmttn commented on pipeline/dbt/snapshots/quality/snps_quality__stats.sql
> +      unique_key="source||'-'||stream",
(je regrette de n'avoir pas utiliser de double dash pour les surrogates)

2024-08-09 10:41 UTC, vmttn commented on pipeline/dags/import_data_inclusion_api.py
> +        trigger_rule=TriggerRule.NONE_SKIPPED,
pas encore bien compris ce commentaire

2024-08-09 10:48 UTC, vmttn commented
> je ne devrais pas merger celle-ci avant celle sur le geocodage 
> au passage y mettre un score supplémentaire sur le nombre de lignes de marts avec un score supérieur à 0.8 ? ou autre ?
>
> Ca permettra de voir l'évolution, sachant que la première sera trompeuse: aujourd'hui on a beaucoup de scores au-delà de 0.8 pour des matchs foncièrement erronés (cf commentaire du second commit de cette PR)

spontanément je serais plutot d'avis de ne pas ajouter cette info. On peut merger et en reparler ensuite si ça te va ? Ca fait déja beaucoup

2024-08-12 08:18 UTC, vperron commented on pipeline/dbt/snapshots/quality/snps_quality__stats.sql
> +        source || '-' || stream AS id,
OK !

2024-08-12 08:18 UTC, vperron commented on pipeline/dbt/snapshots/quality/snps_quality__stats.sql
> +      unique_key="source||'-'||stream",
OK !

2024-08-12 08:19 UTC, vperron commented on pipeline/dags/import_data_inclusion_api.py
> +    generate_source_stats = dbt_operator_factory(
OK !

2024-08-12 08:19 UTC, vperron commented on pipeline/dags/import_data_inclusion_api.py
> +        trigger_rule=TriggerRule.NONE_SKIPPED,
Je le reformule.

2024-08-12 08:24 UTC, vperron commented
OK pour ton dernier commentaire, ça me simplifie la vie ^^

2024-08-12 14:55 UTC, vperron commented on pipeline/dags/import_data_inclusion_api.py
> +        # In that case there is nothing to be snapshotted.
Aujourd'hui, j'ai défini des tests très basiques qui vérifient que on ne "perd" pas une source quelque part.

cf. ici : https://github.com/gip-inclusion/data-inclusion/blob/main/pipeline/dbt/models/intermediate/quality/_quality_models.yml#L51-L79

(d'ailleurs, ils vont trop loin car je ne voulais pas tester le count_contact et count_adresses, on a des sources qui n'en ont pas et c'est "normal".

Du coup ce que j'en comprends pour l'instant:
- je retire tous les data tests actuels, on verra plus tard dans metabase ou dans un second model spécialisé
- je mets les triggers en ALL_DONE pour le nuild et le snapshot de stats pour qu'on ait toujours des données, meme si parfois elles peuvent etre difficiles à interpréter ?

2024-08-12 15:07 UTC, vperron commented on pipeline/dags/import_data_inclusion_api.py
> +        # In that case there is nothing to be snapshotted.
J'ai mis un dernier commit qui reflète cela

2024-08-12 15:24 UTC, vperron commented
cf. ici, apparemment on lance quand meme déjà les stats :shrug: or, rien ne sélectionne explicitement le modèle en question et il n'est pas une dépendance des `marts`. Ou j'ai mal vu un truc ?

2024-08-13 07:23 UTC, vmttn approved these changes

2024-08-13 07:23 UTC, merged