chore(api) : Mention the base_url in the documentation
gip-inclusion/data-inclusion pull request #269
Opened 2024-08-08 13:28 UTC by vperron

Je voulais le faire dans une vue pour récupérer l'objet `request` et en déduire la BASE_URL plutôt que de la mettre dans les settings de l'application, mais cela demandait des changements non triviaux - j'ai préféré garder le changement minimal pour cet impact plutôt mineur.

Le seul endroit où changer le paramètre sera donc dans l'API de staging (default sur prod pour éviter un oubli de paramétrage, comme pour DEBUG)

2024-08-09 09:26 UTC, vmttn requested changes
Je crois qu'il faut update le snapshot syrupy : `pytest --snapshot-update -k openapi`

2024-08-09 09:26 UTC, vmttn commented on api/src/data_inclusion/api/config.py
> +    BASE_URL: str = "https://api.data.inclusion.beta.gouv.fr"
Presque dommage d'avoir à passer cette info :/ on pourrait se servir de la requête mais flemme

2024-08-12 08:03 UTC, vperron commented on api/src/data_inclusion/api/app.py
>          title="data·inclusion API",
Pourquoi pas !
Ce que ça ajoute est ceci:
![image](https://github.com/user-attachments/assets/2a4301b8-e7dc-4726-b8cd-94edaaf293c7)
Mais ça ne change rien par ailleurs (dans les URLs copiées, etc)

J'aime bien conserver la manière que j'ai ajoutée car au moins les gens peuvent copier/coller l'URL.

Perso, je trouve que la mention `servers` avec sa liste déroulante à un seul item et non "copiable" est presque confusante. Mais ça ne coûte pas cher.

2024-08-12 08:03 UTC, vperron commented on api/src/data_inclusion/api/app.py
> +
en effet :)

2024-08-12 08:06 UTC, vperron commented on api/src/data_inclusion/api/config.py
> +    BASE_URL: str = "https://api.data.inclusion.beta.gouv.fr"
Comme je disais dans le commentaire de PR, en effet, la façon clean serait de passer par la requête mais franchement, le nombre de trucs à écrire pour faire ça est 
![image](https://github.com/user-attachments/assets/a15a926e-f936-4045-9779-aab728ebf398)

2024-08-12 09:40 UTC, vmttn commented on api/src/data_inclusion/api/app.py
>          title="data·inclusion API",
100% d'accord
Ce que t'as ajouté est bien plus utile

2024-08-12 09:41 UTC, vmttn commented on api/src/data_inclusion/api/config.py
> +    BASE_URL: str = "https://api.data.inclusion.beta.gouv.fr"
indeed

2024-08-12 12:11 UTC, vmttn approved these changes
lgtm

2024-08-12 13:44 UTC, merged