feat(all) : Récupérer les données géo depuis l'API découpage administratif
gip-inclusion/data-inclusion pull request #282
Opened 2024-08-30 16:27 UTC by vperron

Ceci permet entre autres de:
- récupérer les DOM/TOM
- récupérer l'intégralité des codes EPCIS, Départements, Régions à jour
- les communes ainsi que les arrondissements
- ne plus dépendre ni d'admin_express, ni des exports de l'INSEE
- de ne pas avoir un import séparé dans le pipeline et dans l'API
- passer à un modèle de détection de distance par rapport au centre de la ville et non pas son contour, donc plus performant et avec peu de perte de précision (pas encore réalisé)
- bien d'autres joyeusetés à venir en termes de validation, cohérence, etc

2024-09-02 10:38 UTC, vmttn commented
Je pense qu'il y a moyen de simplifier :speak_no_evil: 

1. On peut se passer du dump des extractions dans s3. Contrairement aux fournisseurs de données, le niveau de service de cette api devrait être bonne et les données relativement stables, en tout cas il n'y a pas de raisons de penser le contraire
2. Séparer clairement les transformations de l'extraction et utiliser dbt pour faire les transfo et le nettoyage des données. L'extraction peut se résumer à quelques appel, du json chargé dans une colonne jsonb, nettoyée par dbt et passée au format tabulaire avec des tests
3. Je ne peux pas m'empêcher de penser qu'on devrait charger les données également dans l'api à partir de l'api découpage. Les données structures/services sont produites par notre pipeline ce qui justifie leur stockage régulier sur s3. Le risque d'incohérence me parait franchement minime et une simple vérification au moment de l'import de nos données devrait suffire à écarter les quelques incohérences qui pourraient se produire si on n'a pas pris le soin de mettre à jour les données découpages dans l'api et la pipeline simultanément

2024-09-02 12:37 UTC, vperron commented
1. OK, ça m'ira toujours de simplifier ! J'ai toujours ce conflit cohérence avec le reste du code VS traitement spécifique.
2. OK aussi, ça me va bien (d'où le wip)
3. A moitié convaincu, car avec ta solution:
  - On a besoin d'un second script d'extraction (similaire mais assez différent, p.ex merger les arrondissements reste valide mais le traitement, création de la table et traitement éventuel sur les colonnes seront en Python/Alembic et non pas en DBT)
  - N'élimine pas le risque d'incohérence, au contraire on en introduit un. OK il suffit d'un check mais ça ajoute un check qui aurait pu être prétesté en pipeline.
  - On n'est pas à l'abri que demain l'API ait besoin d'autres tables venant de notre pipeline pour enrichir les données (voire enrichir les données de commune)
... et encore une fois pour moi ça permet de ne conserver qu'une seule méthode pour charger toutes les données de l'API en un seul coup, ce qui le rend plus simple, solide et facile à maintenir.

2024-09-03 15:53 UTC, vperron commented
A priori, fait les ajustements (grosse maille) que tu voulais voir @vmttn .

2024-09-06 12:55 UTC, vmttn requested changes

2024-09-09 16:40 UTC, vperron commented on pipeline/dbt/models/intermediate/int__union_services__enhanced.sql
> +    SELECT * FROM {{ source('decoupage_administratif', 'departements') }}
Yes, mais on est d'accord que je n'introduis rien de nouveau ici ? Je remplace quelque chose de préexistant ?
Tu veux que je note pour une future PR de ne plus sélectionner les département de cette manière ?

2024-09-09 16:40 UTC, vperron commented on pipeline/dags/sync_cities.py
> +        df = pd.DataFrame(response.json())
Yes
1. j'oublie toujours furl
2. je n'utilise que peu pandas et ne connais pas tout ses fonctionnalités donc merci

2024-09-09 16:40 UTC, vperron commented on pipeline/dbt/models/staging/sources/odspep/stg_odspep__departements.sql
> +-- depends_on: {{ source('decoupage_administratif', 'departements') }}
pas compris la flemme ? j'ai juste remplacé pour que ça continue de fonctionner comme avant. J'ai loupé un truc ?

2024-09-09 16:40 UTC, vperron commented on pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__models.yml
> +              field: code
Yep, bonne idée

2024-09-09 16:40 UTC, vperron commented on pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__models.yml
> +              field: code
Je pense que ce que je peux faire c'est une note dans le YAML en explicitant pourquoi je fonctionne de cette manière: clairement par économie et exception, parce que ça ne sert pas aujourd'hui de faire des tables de staging pour les départements, régions, etc - les données sont réputées fiables et stables. Mais que ce serait la chose a faire.

2024-09-10 08:41 UTC, hlecuyer approved these changes

2024-09-10 08:55 UTC, vmttn commented on pipeline/dbt/models/staging/sources/odspep/stg_odspep__departements.sql
> +-- depends_on: {{ source('decoupage_administratif', 'departements') }}
t'as zapé l'étape "staging" :)

2024-09-10 08:58 UTC, vmttn commented on pipeline/dags/sync_cities.py
> +        df = pd.DataFrame(response.json())
np !

2024-09-10 16:23 UTC, vperron commented
Remarques traitées et commandes d'import des communes restaurée coté API.

2024-09-12 08:03 UTC, vmttn requested changes

2024-09-12 08:03 UTC, vmttn commented on pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__models.yml
> +          - dbt_utils.not_empty_string
`not_null` ?

2024-09-12 08:33 UTC, vperron commented on api/src/alembic/versions/20240830_175854_e3f3dfa4ad01_modified_api__communes.py
> +    )
bien vu :)

2024-09-12 08:33 UTC, vperron commented on api/tests/e2e/api/test_inclusion_data.py
>          pytest.param(PARIS, PARIS["code_insee"], True, marks=pytest.mark.xfail),
Ah ben oui, j'avais meme pas intuité.

2024-09-12 08:33 UTC, vperron commented on pipeline/dbt/models/staging/decoupage_administratif/_decoupage_administratif__models.yml
> +          - dbt_utils.not_empty_string
ok !

2024-09-13 15:49 UTC, merged