Hlecuyer/feat/mes aides/integration aides permis velo
gip-inclusion/data-inclusion pull request #296
Opened 2024-09-17 14:25 UTC by hlecuyer

2024-09-17 15:37 UTC, hlecuyer commented
Dependant de cette PR => https://github.com/gip-inclusion/data-inclusion/pull/270

2024-09-18 10:21 UTC, vmttn requested changes
1ère passe rapide :)

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/_mes_aides__models.yml
> +  - name: int_mes_aides__adresses_permis_velo
```suggestion
  - name: int_mes_aides_permis_velo__adresses
```

ou

```suggestion
  - name: int_mes_aides_aides__adresses
```

selon ce que tu choisis de garder

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/_mes_aides__models.yml
> +  - name: int_mes_aides__structures_permis_velo
cf plus haut :point_up:

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/_mes_aides__models.yml
> +  - name: int_mes_aides__services_permis_velo
:point_up:

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__services_permis_velo.sql
> +zone_diffusion AS (
```suggestion
zones_diffusion AS (
```

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__services_permis_velo.sql
est-ce que tu peux utiliser le pluriel pour le nom de table & cte ?

faudrait qu'on finisse par mettre quelques guidelines au propre :sweat_smile:

2024-09-18 10:21 UTC, vmttn commented on pipeline/dags/dag_utils/sources/__init__.py
> +            "permis_velo": {
j'ai l'impression que `permis_velo` que tu as ajouté correspond aux données `aides` qui étaient déjà récupérées

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__services_permis_velo.sql
> +            WHEN permis_velo.mode_acceuil = TRUE THEN ARRAY['a-distance']
```suggestion
            WHEN permis_velo.mode_accueil = TRUE THEN ARRAY['a-distance']
```

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
> +        CAST(data #>> '{fields,En ligne}' AS BOOLEAN)                          AS "mode_acceuil",
```suggestion
        CAST(data #>> '{fields,En ligne}' AS BOOLEAN)                          AS "mode_accueil",
```

2024-09-18 10:21 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
le staging doit contenir juste un premier nettoyage basique des données brutes :

* passage du colonne jsonb `data` à des colonnes bien typées
* formattage des noms de colonnes (e.g. `{fields,Liaisons Régions}` en `liaisons_regions`, etc.) sans introduire de synonymes ou à mapper.
* type casting, avec le bon parsing (e.g. les dates)
* correction à la marge qu'il vaut mieux faire tout de suite et oublier, genre des sirets qui auraient perdu leur leading 0, etc.

tout ce qui relève du mapping est à mettre dans intermediate

pq ?

* staging : on se préoccupe des données brutes indépendemment du schéma data·inclusion, on peut parler directement d'un champ producteur sans avoir à prendre en compte un changement nom
* intermediate : on se préoccupe du schéma
* les données staging peuvent être inspectées par le métier
* ...

2024-09-18 12:14 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
> +            data #>> '{fields,Liaisons Départements}' FROM POSITION('-' IN data #>> '{fields,Liaisons Départements}') + 1  -- noqa
La ligne ne passe pas le parsing. Je peux essayer d'afiner mais je n'ai pas compris pourquoi il avait une erreur de parsing ici.

2024-09-18 12:20 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
Ok pour les noms des colonnes.
Est ce que je doit passer:
```
        SUBSTRING(
            data #>> '{fields,Liaisons Départements}' FROM POSITION('-' IN data #>> '{fields,Liaisons Départements}') + 1  -- noqa
        ) 
```
selon toi ?

2024-09-18 13:33 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
* pour Liaisons Villes : ça me parait bien de garder ça dans staging. Je renommerais en `liaisons_villes__nom_commune` et `liaison_villes__code_postal`

2024-09-18 13:37 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
> +            data #>> '{fields,Liaisons Départements}' FROM POSITION('-' IN data #>> '{fields,Liaisons Départements}') + 1  -- noqa
je pense que tu peux supprimer cette colonne, cf mon commentaire plus haut

2024-09-18 13:40 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
pour `Liaisons Départements` : après inspection des autres champs dispos dans les données brutes, je pense qu'on n'a pas besoin d'utiliser `Liaisons Départements`. Il y a une colonne `N° Départements` qui contient juste le code. Pour récupérer un label propre (si jamais c'est nécessaire), on pourra utiliser les tables du découpage administratif.

2024-09-18 13:44 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
j'éviterais l'usage toutes les colonnes qui utilisent des labels, surtout s'il y a une colonne avec un code qui permet de le déduire, directement ... ou indirectement : par exemple tu peux déduire la région du code département

2024-09-18 13:52 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
> +        TRIM(SUBSTRING(data #>> '{fields,Liaisons Villes}' FROM '^(.*) \('))   AS "ville_nom",
attention il y a plusieurs villes dans `Liaisons Villes` :)

il faudrait plutot extraire une colonne TEXT[][] contenant par exemple : `{{Lille, 59000}, {Hellemmes, 59260}}`

2024-09-18 14:02 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__structures_permis_velo.sql
> +        MAX(id)                     AS "adresse_id",
j'imagine que tu as voulu éliminer des doublons.

Pour faire ça :

```sql
SELECT DISTINCT ON (COALESCE(siret_structure, id))
    siret_structure  AS "id",
    id                      AS "adresse_id",
    ...
    FROM permis_velo
```

2024-09-18 14:03 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__structures_permis_velo.sql
> +        MAX(id)                     AS "adresse_id",
accessoirement ça te permet de retirer l'union

2024-09-19 12:47 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
ok

2024-09-19 12:47 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/mes_aides/stg_mes_aides__permis_velo.sql
> +        TRIM(SUBSTRING(data #>> '{fields,Liaisons Villes}' FROM '^(.*) \('))   AS "ville_nom",
Antoine a fait une remarque la dessus, il faudra peut etre faire un service par ville

2024-10-17 14:13 UTC, vmttn requested changes
pas grand chose à dire, c'est propre :sparkles: juste quelques renommages + quelques tests à ajouter pour bien dormir :sleeping:

2024-10-17 14:13 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__permis_velo__structures.sql
> +            WHEN permis_velo.typologie_structure LIKE '%Mission locale%' THEN ARRAY['mission-locale']
insensible à la casse

```suggestion
            WHEN permis_velo.typologie_structure ~* 'mission locale' THEN ARRAY['mission-locale']
```

2024-10-17 14:13 UTC, vmttn commented on pipeline/dbt/models/staging/sources/mes_aides/_mes_aides__models.yml
> +  - name: stg_mes_aides__permis_velo
est-ce que tu pourrais ajouter quelques `data_tests` ? au minimum je dirais : 

* `id` : `not_null`, `dbt_utils.not_empty_string`, `unique`
* `date_maj` : `not_null`, `not_constant`

mais je pense que ça serait bien de faire quelques checks sur les *valeurs prédéfinies*. Par exemple, le champ `type` contient `Aide financière`, `Prestation` et `Accompagnement` et ton mapping en dépend. Si une de ces valeurs est renommée, ça sera complément silencieux, il n'y aura plus de mapping.

Pour tester ça simplement, je dirais qu'il faut faire comme pour fredo : dans `models/staging/sources/mes_aides/` voir `models/staging/sources/mes_aides/permis_velo` tu crées des models supplémentaires où tu `UNNEST` : `stg_mes_aides__permis_velo__types`, etc. et là tu peux ajouter un `data_test` de type `accepted_values`.

(d'ailleurs je n'ai pas mis de tests pour les garages c'est dommage :))

2024-10-22 16:03 UTC, vmttn approved these changes

2024-10-22 16:07 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__permis_velo__services.sql
> +),
@vmttn

2024-10-22 16:17 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__permis_velo__services.sql
> +),
je check ça jeudi

2024-10-24 09:04 UTC, vmttn approved these changes

2024-10-24 11:00 UTC, vmttn approved these changes

2024-10-24 12:40 UTC, merged