feat(brevo) : Hide contacts properly for all sources
gip-inclusion/data-inclusion pull request #303
Opened 2024-09-23 13:33 UTC by vperron

When a contact has stated an opposition and/or has been blacklisted, handle it correctly, whatever the source.

This time, it is also properly tested.

2024-09-27 13:37 UTC, vmttn commented on pipeline/dbt/models/intermediate/int__union_services.sql
> +    WHERE est_interdit = TRUE
```suggestion
    WHERE est_interdit
```

2024-09-27 13:38 UTC, vmttn commented on pipeline/dbt/models/intermediate/int__union_services.sql
> +        UNNEST(contact_uids) AS id,
```suggestion
    SELECT
        DISTINCT UNNEST(contact_uids) AS id,
```

2024-10-01 15:20 UTC, vperron commented on pipeline/dbt/models/intermediate/int__union_services.sql
> +    WHERE est_interdit = TRUE
ok !

2024-10-01 15:20 UTC, vperron commented on pipeline/dbt/models/intermediate/int__union_services.sql
> +        UNNEST(contact_uids) AS id,
c'est pas moi c'est sqlfluff.

2024-10-01 15:54 UTC, vperron commented
Je m'attends à une relecture plus musclée :)

2024-10-08 15:38 UTC, vperron commented
@vmttn cette PR est un peu tricky je serais content d'avoir ton avis à ce sujet.

@Caldagues je vais ajouter à cette PR l'implémentation pour cacher les contacts d'une structure également si on a eu opposition sur un email venant d'un service.

2024-10-17 15:41 UTC, vmttn commented on .pre-commit-config.yaml
> +    rev: v0.6.8
à priori on peut maintenant retirer [cette ligne](https://github.com/gip-inclusion/data-inclusion/blob/54d5d766e0fa8c4002171c11e4fbdd92284b767d/api/pyproject.toml#L20C1-L20C39) car depuis 0.6 `src` layout est bien géré dans les imports

2024-10-18 14:09 UTC, vmttn requested changes

2024-10-18 14:13 UTC, vmttn commented on pipeline/dbt/models/intermediate/int__union_services.sql
> +contacts_opposes AS (
nit : il me semble que la bonne formulation en anglais c'est "object to"

2024-10-18 14:14 UTC, vmttn commented
1. j'ai rebased sur main
2. j'ai séparé les bump des precommits dans #323 , où l'on pourra s'occuper de nettoyer pour respecter les règles
3. j'ai ajouté un commit `wip` qui prend en compte l'ensemble des retours

2024-10-18 14:16 UTC, vmttn commented
@vperron je te laisse check les changements et réécrire le test de la :skull: qui devrait être plus simple là (plus besoin de se prendre la tête avec les 15 tables de l'union)

2024-10-21 14:15 UTC, vperron commented on .pre-commit-config.yaml
> +    rev: v0.6.8
Intéressant pour les règles de lint FastAPI. Je ne me le mets pas sur le chemin critique cependant, et je suis un peu résistant à l'idée de créer un ticket également; en effet j'ai l'impression que on a déjà énormément de tickets techniques dans le backlog, peut etre que il faut éviter de trop en ajouter.

2024-10-21 14:16 UTC, vperron commented on pipeline/dbt/models/intermediate/int__union_services.sql
> +),
oh nice, c'est vrai ça ! merci !

2024-10-21 14:18 UTC, vperron commented on .pre-commit-config.yaml
> +    rev: 3.2.0
Vu et approuvé la PR dédiée

2024-10-21 14:18 UTC, vperron commented on pipeline/dbt/models/intermediate/_models.yml
Yes en effet, il ne me mettait pas à l'aise non plus

2024-10-21 14:26 UTC, vperron commented on pipeline/dbt/models/intermediate/int__union_contacts__enhanced.sql
> +        CASE WHEN rgpd_notices.id IS NULL OR NOT rgpd_notices.was_objected_to THEN contacts.courriel END           AS "courriel",
Pour moi il manque quand même une condition sur `rgpd_notices.has_hardbounced` ici, je la rajouterai et vérifierai avec le test

2024-10-21 16:44 UTC, vperron commented
@vmttn j'ai ajouté un commit qui redresse le test et corrige quelques erreurs au passage qui empêchaient le code de tourner.

En particulier, nombre de sources ou streams n'ont pas de `contact_nom_prenom`; en bonus, je retire le filtre que nous faisions sur le fait que l'on ne voulait que des `services` dans l'union de contacts, je pense que c'etait un héritage malheureux qu'on  a pas besoin de conserver pour l'instant.

2024-10-22 08:14 UTC, vmttn approved these changes

2024-10-22 08:25 UTC, vperron commented
Je squash, je me demande si ça vaut le coup de le déployer en staging parce que:
- staging n'a pas la clé Brevo et je ne suis pas sur que ça vaille le risque
- de toutes façons pour que Antoine valide ça c'est un peu une tannée, il faudrait qu'il suive dans le code le jeu des tables de contacts, je pense que il vaut mieux que je le valide moi meme en prod en mettant un cas explicite dans le ticket 

OK pour toi ?

2024-10-22 11:43 UTC, merged