fix(dora): fix dora services rejected by the quality check
gip-inclusion/data-inclusion pull request #311
Opened 2024-10-03 13:53 UTC by YannickPassa

2024-10-03 14:05 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +            ELSE ARRAY(SELECT services.frais WHERE services.frais IS NOT NULL)
a priori pas besoin du SELECT ?

je vais te demander d'ecrire un petit test unitaire (`unit_test` ) pour ces deux cas pour vérifier que la logique fonctionne. OK ?

2024-10-03 14:05 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +        CASE
https://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/

je serais content qu'on explique ici avec un commentaire pourquoi on a décidé de mettre NULL si un seul des modes d'orientation est "pro" ? 
Pourquoi on a pas décidé d'ignorer tout le service carrément, ou de retirer ce mode si d'autres sont dispo ?

Bref, un commentaire ici permettra aux futurs dev de comprendre le pourquoi de ce code si jamais ils veulent etre en capacité de le modifier.

Ne doit-on pas demander à Dora pourquoi ils nous envoient cette valeur au fond, dans leur API ? Ils pourraient pas filtrer eux memes ?

2024-10-16 13:25 UTC, YannickPassa commented on pipeline/dbt/models/intermediate/_models.yml
> +      - {id: foo,'structure_id':08887e14-cd85-4ec8-85cb-bb7b88d32985,'frais':ARRAY['foo']}
@vperron si je retire 'frais' ça marche nickel

2024-10-17 13:35 UTC, vperron commented on pipeline/dbt/models/intermediate/_models.yml
> +      - {id: foo,'structure_id':08887e14-cd85-4ec8-85cb-bb7b88d32985,'frais':ARRAY['foo']}
Désolé, pas eu le temps de m'y mettre hier j'y retourne.

2024-10-17 14:16 UTC, vperron commented
@YannickPassa tu peux regarder mon fix, tu n'etais pas loin mais pas possible d'utiliser le mode "dict" pour ton expectation ici.

Regarde bien mon commit, le commentaire du commit, et le fait que en effet comme j'avais supposé, le SELECT dans le ARRAY était en trop !

Les tests passent, maintenant on va voir une cool couverture / fixtures de base pour jouer avec Dora, c'est cool.

2024-10-17 14:16 UTC, vperron commented
Je n'ai pas encore fait de relecture globale, dis moi si et quand tu en as envie

2024-10-17 14:21 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +            ELSE ARRAY(SELECT services.frais WHERE services.frais IS NOT NULL)
Il etait bien superflu et faussait les résultats, mais relis pour etre sur.

2024-10-17 14:21 UTC, vperron commented on pipeline/dbt/models/intermediate/_models.yml
> +      - {id: foo,'structure_id':08887e14-cd85-4ec8-85cb-bb7b88d32985,'frais':ARRAY['foo']}
Fait

2024-10-17 14:24 UTC, YannickPassa commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +            ELSE ARRAY(SELECT services.frais WHERE services.frais IS NOT NULL)
Purée ok, j'avais testé sans mais j'ai du faire une connerie. Merci bcp !

2024-10-17 14:24 UTC, YannickPassa commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +            ELSE ARRAY(SELECT services.frais WHERE services.frais IS NOT NULL)
Je récupère chez moi et je regarde

2024-10-18 04:58 UTC, YannickPassa commented
> Je n'ai pas encore fait de relecture globale, dis moi si et quand tu en as envie

C bon pour ta dernière (j'espère) relecture !

2024-10-21 08:07 UTC, vmttn requested changes

2024-10-21 08:07 UTC, vmttn commented on pipeline/dbt/models/intermediate/_models.yml
> +        fixture: stg_dora__services__input
intéressant ces fixtures :bulb: 

Mais pas convaincu qu'on préfère ça au dict inline pour un setup aussi simple :thinking: 

```suggestion
      - input: ref('stg_dora__services')
        rows:
          - {frais: '{gratuit}'}
```

1. on perd la possibilité de lire le test d'un seul coup de d'oeil. Il faut ouvrir 3 fichiers.
2. si la fixture est partagée comme tu l'imagines, on risque de se prendre la tête pour ne pas casser d'autres tests.
3. **imaginons** que le champ `frais` de dora puisse contenir `gratuit` et `{gratuit}` : on devrait ajouter un test case, 1 pour `gratuit` et un pour `{gratuit}`. Avec le dict inline, pas compliqué, il suffit d'ajouter une ligne. Avec la fixture "de base", ça va devenir beaucoup trop verbeux.

2024-10-21 08:07 UTC, vmttn commented on pipeline/dbt/models/intermediate/_models.yml
> +        fixture: stg_dora__services__input
plein de réflexions pour un truc finalement assez simple, mais essentiel de s'accorder sur notre façon de procéder !

2024-10-21 08:07 UTC, vmttn commented on pipeline/dbt/models/intermediate/_models.yml
> +  - name: test_charges_null_is_really_null
```suggestion
  - name: test_frais_null_is_really_null
```

2024-10-21 08:07 UTC, vmttn commented on pipeline/dbt/models/intermediate/_models.yml
> +  - name: test_charges_null_is_really_null
pas besoin de traduire les mots métiers

2024-10-21 08:07 UTC, vmttn commented on pipeline/dbt/models/intermediate/_models.yml
> +    description: "Check if the NULL value in the stg file stays null and is not converted to {NULL}"
bon réflexe, mais je pense qu'en repassant sur un simple dict inline, cette description sera en trop

2024-10-21 08:57 UTC, vperron commented on pipeline/dbt/tests/fixtures/int_dora__services__expected.sql
ça faisait partie de mes remarques, je n'ai pas réussi à activer encore DBT sur ces fichiers, je le laissais en exercice à Yannick ^^

2024-10-21 09:01 UTC, vperron commented on pipeline/dbt/models/intermediate/_models.yml
> +          select ARRAY['services:bar'] as contact_uids, TRUE as est_interdit, '2021-01-01' as date_di_rgpd_opposition
Le problème comme je le disais à Yannick est que les unit tests DBT ne supportent pas les arrays en Postgres.
![image](https://github.com/user-attachments/assets/7435ccba-2e74-4d12-9c4e-6b0f939a288f)
https://docs.getdbt.com/reference/resource-properties/data-types

On ne peut donc pas utiliser les `dict` ici... Et c'est bien dommage car en SQL il n'y a plus de type inference et on doit donc remplir toutes les colonnes.

2024-10-21 09:01 UTC, vperron commented on pipeline/dbt/models/intermediate/_models.yml
> +        fixture: stg_dora__services__input
J'adorerais faire le dict inline mais cf ma reponse ci-dessus (les ARRAY posent souci, le JSON ne le poserait pas)

2024-10-22 13:01 UTC, YannickPassa commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +            WHEN blocked_services_uids.id IS NULL
merci !

2024-10-23 07:42 UTC, merged