feat(pipeline) : Simplify notify_rgpd_contacts
gip-inclusion/data-inclusion pull request #326
Opened 2024-10-24 13:36 UTC by vperron

After an entire year of operation, we noticed that our sources never change their contact emails. Ever.

Even if someday this happens, we can probably suppose that it's till going to be quite rare.

In those exceptional cases, it means that the structure would get a new RGPD notification.

But it does make the code way easier to maintain and more robust:
- now we will never miss an email that would have been "forgotten" by Brevo (due to rate limits, payment issues, ...)
- it can also be seen as a feature to send a new notification if the email changes, for instance when the previous one was incorrect.

Moreover, we don't need to maintain the `contact_uid` list that was sent to brevo.

2024-10-24 13:37 UTC, vperron commented on pipeline/dbt/models/intermediate/_models.yml
> -        - {source: autre, id: solo, courriel: solo@autre.net, contact_nom_prenom: Autre Personne, telephone: '06666666'} # hardbounce : only email is hidden
oui, ce test était commité cassé. :x

2024-10-28 09:50 UTC, vmttn requested changes
est-ce qu'il y a une migration de données à prévoir sur brevo ?

2024-10-28 09:50 UTC, vmttn commented on pipeline/dbt/models/intermediate/int__union_contacts__enhanced.sql
> +        has_hardbounced IS TRUE AS has_hardbounced_truthy
cette colonne n'est jamais vide

![image](https://github.com/user-attachments/assets/e1196757-c059-45cb-bbe8-4fcf7ffc625d)

2024-10-28 09:50 UTC, vmttn commented on pipeline/dbt/models/intermediate/int__union_contacts__enhanced.sql
> +        contacts.courriel                     AS "_courriel_original",
j'ai l'impression que ce champ a 2 fonctions ici :

1. permettre d'avoir la vue avant/après
2. permettre de récupérer la liste des mails à charger dans brevo

Pour 1. , ça n'est pas nécessaire. Il suffira de faire une jointure avec `int__union_contacts`.

Pour 2., cf commentaire plus haut

2024-10-28 09:50 UTC, vmttn commented on pipeline/dags/notify_rgpd_contacts.py
> +    all_contacts = [c[0] for c in contacts]
:heart:

2024-10-28 09:50 UTC, vmttn commented on pipeline/dags/notify_rgpd_contacts.py
> +            """
pourquoi utiliser `rgpd_notice_has_hardbounced` ?

utiliser `int__union_contacts` serait moins compliqué (pas de rétroaction)

2024-10-28 09:50 UTC, vmttn commented on pipeline/RGPD.md
> +que aucune source ne modifiait ses courriels; nous avonc donc cessé de maintenir ce système complexe, mais il en
très bien :+1:

2024-10-29 10:18 UTC, vperron commented
Pas de migration de données à prévoir sur Brevo.
Les listes seront mises à jour automatiquement, la seule chose différente est que certains champs que l'on uploadait auparavant (les contact_uids) ne seront plus mis à jour ni utilisés, mais inutile de les "nettoyer".

2024-11-04 15:48 UTC, vmttn approved these changes

2024-11-13 10:27 UTC, merged