feat(profils): add profils search full text to api
gip-inclusion/data-inclusion pull request #329
Opened 2024-10-28 14:35 UTC by hlecuyer

2024-10-31 13:12 UTC, vmttn requested changes
ok 1ère passe ! c'est cool

je n'ai pas vraiment fait la revue de code côté api

avant, est-ce que tu peux ajouter un test dédié, et quelques tests cases ? (sans tester la logique websearch).

2024-10-31 13:12 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
> +        'personnes en situation de handicap'                         AS "profils_precisions",
```suggestion
        NULL                        AS "profils_precisions",
```

2024-10-31 13:12 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/action_logement/int_action_logement__services.sql
> +        ARRAY_TO_STRING(services.profils, '')            AS "profils_precisions",
```suggestion
        NULL            AS "profils_precisions",
```

2024-10-31 13:12 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +        ARRAY_TO_STRING(services.profils, ', ')          AS "profils_precisions",
là ok :+1:

2024-10-31 13:12 UTC, vmttn commented on deployment/MIGRATION.md
> +   ssh root@163.172.171.247
```suggestion
   ssh root@<INSTANCE_DNS>
```

2024-10-31 13:22 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
> +        ('men', 'homme', 'adultes'),
Le mapping etait propose par Antoine, ca me va de ne rien mettre.

2024-10-31 13:23 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/monenfant/int_monenfant__services.sql
> +        'famille enfant'                                                                  AS "profils_precisions",
Oui je peux concatener les colonnes cote api

2024-10-31 14:59 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__lieux.sql
> +        )                                                              AS "publics__other",
Oui je ne l'ai pas fait pour 2 raisons:
 - Antoine n'a pas mis de mapping sur ce champs pour `profils`
 - Je trouvais quand meme ce champs interessant a ajouter, mais ca ressemble beaucoup a un fourre tout donc je me suis dit que cela ne valais pas le coup de le maintenir (traduction et tests). La comme, ca c'est du bonnus, et si soliguide propose une vrai api en francais un jour, ca sera encore mieux.

Mais je te laisse arbitrer, je peux effectivement faire la meme chose que pour les autres ou le virer.

2024-10-31 15:19 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__permis_velo__services.sql
> +        permis_velo.autres_conditions                              AS "profils_precisions",
tu veux que je rajoute un truc ?

2024-11-04 15:51 UTC, vmttn commented on pipeline/dbt/models/intermediate/sources/mes_aides/permis_velo/int_mes_aides__permis_velo__services.sql
> +        permis_velo.autres_conditions                              AS "profils_precisions",
non on va regarder ce que ça donne

2024-11-04 16:12 UTC, vmttn commented on pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__lieux.sql
> +        )                                                              AS "publics__other",
alors en regardant les valeurs dans ce champs, il y a par exemple `student` ou encore `handicap`. Potentiellement intéressant.

Par contre quasiment tous les lieux ont ces valeurs définies... ça perd un peu de son sens... genre 93% des lignes ont toutes les valeurs possible définies

[cf](https://metabase.data.inclusion.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJkYXRhYmFzZSI6OSwibmF0aXZlIjp7InF1ZXJ5IjoiV0lUSCBzb3VyY2UgQVMgKFNFTEVDVCAgKiBGUk9NIHNvbGlndWlkZS5saWV1eCksXG5cbmZvbyBBUyAoXG4gICAgU0VMRUNUXG4gICAgICAgIGRhdGEgLT4-ICdsaWV1X2lkJyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEFTIFwibGlldV9pZFwiLFxuICAgICAgICBUUklNKEpTT05CX0FSUkFZX0VMRU1FTlRTX1RFWFQoZGF0YSAtPiAncHVibGljcycgLT4gJ290aGVyJykpIEFTIFwidmFsdWVcIlxuICAgIEZST00gc291cmNlXG4gICAgV0hFUkUgZGF0YSAtPiAncHVibGljcycgLT4gJ2dlbmRlcicgSVMgTk9UIE5VTExcbiksXG5cbmJhciBBUyAoXG5TRUxFQ1QgdmFsdWUsIGNvdW50KERJU1RJTkNUIGxpZXVfaWQpIEFTIGNvdW50IEZST00gZm9vIEdST1VQIEJZIEdST1VQSU5HIFNFVFMgKCgxKSwgKCkpIE9SREVSIEJZIDIgREVTQ1xuKVxuXG5TRUxFQ1RcbiAgICB2YWx1ZSwgKDEwMCAqIGNvdW50IC8gTUFYKGNvdW50KSBPVkVSICgpKSB8fCAnJSdcbkZST00gYmFyIiwidGVtcGxhdGUtdGFncyI6e319fSwiZGlzcGxheSI6InRhYmxlIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9LCJ0eXBlIjoicXVlc3Rpb24ifQ==)

2024-11-04 16:21 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/soliguide/stg_soliguide__lieux.sql
> +        )                                                              AS "publics__other",
A oui c'est nase, autant ne pas le mettre du coup, non ?

2024-11-13 11:40 UTC, vperron requested changes
Je verrais bien une petite discussion autour du design de cette PR car je ne suis étonné par certains choix:
- introduction d'un nouveau query parameter et son utilisation pour filtrer
- introduction d'un nouveau champ et choix des valeurs possible pour ce dernier

Par ailleur, attention aux refactors purement de doc, de SQLFluff et celui concernant Soliguide, qui me praissent tous mériter leur propre commit voire PR.

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
> +        NULL                                                         AS "profils_precisions",
ah bon ? Pourquoi ne pas proposer `personnnes en situation de handicap` ?

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/data_inclusion/int_data_inclusion__services.sql
> +        ) AS TEXT [])                                    AS "profils",
note : pareil, tout cela sera à mettre dans un commit SQLFluff séparé.

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/dora/int_dora__services.sql
> +        CAST(services.date_suspension AS DATE)           AS "date_suspension",
même remarque (commit séparé sqlfluff)

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/france_travail/int_france_travail__services.sql
> +        NULL                                             AS "profils_precisions",
J'ai du mal à suivre pourquoi parfois on met `ARRAY_TO_STRING(services.profils, ', ')` et d'autres fois, NULL. 
Peut-être peut on l'expliquer en commentaire quelque part ?

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
> +    SELECT * FROM {{ ref('stg_soliguide__lieux__publics__familliale') }}
nit: il y a une faute de frappe ici non ? dans `familliale`. 

supernit : pourquoi on a subitement "gender" (en anglais) au lieu de "genre" quand tout le reste est en français ? Soyons cohérents !

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
> +  - name: stg_soliguide__lieux__publics__familliale
nit: faute de frappe

2024-11-13 11:40 UTC, vperron commented on pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
> +              values: ['regular', 'asylum', 'refugee', 'undocumented']
je serais très heureux que l'on découpe en plusieurs PR cette PR.

- une PR qui fait les mises à jour SQLFluff de style un peu partout (les CAST etc)
- une PR qui fait ce refactor de Soliguide
- une PR qui réalise la recherche full text

2024-11-13 11:40 UTC, vperron commented on pipeline/pyproject.toml
> +preferred_type_casting_style = "cast"
yes, ce changement et son impact doit etre dans une PR à part je dirais.

2024-11-13 11:40 UTC, vperron commented on api/CONTRIBUTING.md
> +python src/data_inclusion/api/cli.py import_communes
commit à part pour ce changement :)

2024-11-13 11:40 UTC, vperron commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +               ' '||
attention à ne pas se retrouver avec beaucoup de profils_precisions qui valent " " du coup :) Faudrait un dernier COALESCE pour avoir une valeur NULL ou '' non ?

2024-11-13 11:40 UTC, vperron commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +        CREATE OR REPLACE FUNCTION immutable_to_tsvector(
je ne suis pas ultra fan de ce nom un peu générique alors que la fonction n'agit que sur des champs bien spécifiques. Que penses-tu plutot de `generate_profils_precisions()` ?

2024-11-13 11:40 UTC, vperron commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +            "profils_precisions",
Personnellement, je l'aurais plutot nommée `profils_ts` ou `profils_search` cette colonne ? Dans les faits il ne s'agit pas tant de précisions que d'un tsvector. 

Cela apporterait sinon de la confusion avec le keyword `profils_precisions` que tu proposes en keyword au niveau de l'API.

D'ailleurs, je suis étonné que l'on introduise ce nouveau keyword dans l'API; il me semblait que la logique était de proposer toujours la liste de profils dans la recherche, sauf que au lieu de simplement matcher sur les profils, on fait une recherche full text sur ce champ également. Non ?

En tout cas, à l'ère du chantier de simplification du schéma et de l'API, je trouve que proposer un nouveau keyword de recherche potentiellement en conflit avec le `profils` est dommage.

Ma proposition:
- on garde uniquement `profils` comme query param dans l'API 
- on recherche les profils qui marchent à 100% comme avant
- on y ajoute les services dont le recherche full text matche aussi

Peut etre que je loupe une info importante cela dit, a dispo pour en discuter avec @vmttn et toi !

2024-11-13 11:40 UTC, vperron commented on api/src/data_inclusion/api/inclusion_data/models.py
> +            "to_tsvector('french', COALESCE(profils_precisions, ''))", persisted=True
tiens, pourquoi ici on ne prend pas en compte `profils` contrairement à plus haut ? Ca me parait mériter un commentaire a minima.

2024-11-13 11:40 UTC, vperron commented on api/src/data_inclusion/api/inclusion_data/services.py
> +        )
ah donc on autorise la websearch ? Pourquoi ? Auquel cas il faudra documenter tout cela. Et par ailleurs je pense que ça vaut le coup de documenter le `bool_p('@@')` et le reste via un commentaire ici.

2024-11-14 09:29 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
> +        NULL                                                         AS "profils_precisions",
J'ai join les 2 colonnes cote api pour la recherche full text.

2024-11-14 09:33 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
> +        CAST((services.attributes__changed) AS DATE)                 AS "date_maj",
Je le prend en comte pour ma prochaine PR mais le faire apres coup sur tous les fichiers va me prendre trop de temps si c'est ok pour toi.

2024-11-14 09:34 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/data_inclusion/int_data_inclusion__services.sql
> +        ) AS TEXT [])                                    AS "profils",
ce fichier va partir dans le rebase

2024-11-14 09:41 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
> +    SELECT * FROM {{ ref('stg_soliguide__lieux__publics__familliale') }}
Pas si nit que ca, bien vu...

2024-11-14 09:57 UTC, hlecuyer commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +            "profils_precisions",
La colonne ts_vector est a part => `searchable_index_profils_precisions`.
Pour le coup, il s'agit vraiment de precisions pour les profils, mais on peut discuter du nom du champs.

> D'ailleurs, je suis étonné que l'on introduise ce nouveau keyword dans l'API; il me semblait que la logique était de proposer toujours la liste de profils dans la recherche, sauf que au lieu de simplement matcher sur les profils, on fait une recherche full text sur ce champ également. Non ?

Le ticket n'est pas explicite la dessus donc j'ai fait ce qu'il me parraissait le mieux. Je trouve que c'est bien de garder le fonctionnement du filtre tel qu'il est aujourd'hui pour 2 raisons:
 - On ne casse/change rien, donc pas de problemes de retrocompatibilite (ca pourrais etre bizarre de se retrouver du jour au lendemain avec beaucoup plus de resultat sur le meme filtre).
 - Les utilisations de filtres sont plus facilement explicable donc plus facile de reperer des bugs a l'utilisation (ou d'ajuster les paramettres de la recherche full text)
 
 Si tous nos utilisateurs n'utilise plus le premier filtre, on pourra toujours l'enlever plus tard. Contre partie, c'est plus difficile a deployer.

2024-11-14 10:47 UTC, hlecuyer commented on api/src/data_inclusion/api/inclusion_data/services.py
> +        )
Tres arbitraire comme decision :)
Je l'ai fait par simplicite. La fonctionalite est fait pour dependre de l'input du user, ne fail pas et propose des fonctionalites/syntax qu'on retrouve sur d'autres moteurs de recherches du coup je pensais que c'etait adapte.
Sinon il faut nous meme faire des regles et les implementer dans le code, faire de la gestion d'erreur par dessus.
Ca repasse par une couche de specification.

Je peux mettre un commentaire pour l'operateur. Mais en gros c'est la syntax sqlalchimie que j'ai trouver pour faire ce type de query:
```sql
SELECT to_tsvector('fat cats ate fat rats') @@ websearch_to_tsquery('fat AND rat');
```
Je peux renvoyer a la documentation postgres si besoin ?

2024-11-14 10:50 UTC, hlecuyer commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +               ' '||
Il n'y a pas de tokenisation pour les espaces donc c'est pas grave en soit. Je peux le rajouter pour eviter qu'on se repose la question par la suite.

2024-11-14 10:58 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/france_travail/int_france_travail__services.sql
> +        NULL                                             AS "profils_precisions",
Valentin me l'a fait changer et j'ai oublier de le faire sur action logement, mais globalement la regle c'est si il n'y a pas d'info supplementaire a mettre, on met le champs a NULL

2024-11-14 10:59 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
> +    SELECT * FROM {{ ref('stg_soliguide__lieux__publics__familliale') }}
> supernit : pourquoi on a subitement "gender" (en anglais) au lieu de "genre" quand tout le reste est en français ? Soyons cohérents !

Ca c'est soliguide, j'ai repris leur nom de champs dans staging. La coherence est plus dans les convention de nommage staging qui veut qu'on se rapproche au plus de ce qu'on recoit non?

2024-11-14 11:02 UTC, hlecuyer commented on api/src/data_inclusion/api/inclusion_data/models.py
> +            "to_tsvector('french', COALESCE(profils_precisions, ''))", persisted=True
Bien vu...
Je ne sais pas si ca change grand chose, je ne maitrise pas les arcannes de sqlalchemy mais c'est un oublie de ma part...

2024-11-14 18:58 UTC, vperron commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +            "profils_precisions",
Vu en réunion, OK pour conserver et une colonne à part et un keyword, qui devra quand meme refléter plus sa fonction (comme `profil_query` ou `profil_search` ? ) ; les deux seront non documentés ni reflétés dans le schéma et proposés à des fins de test pour que l'on puisse a terme choisir d'un fonctionnement vs un autre.

Idéalement il faudra pouvoir mesurer lequel des keywords, et lequel de ces champs, sera le plus utile ou utilisé par les consommateurs et n'en garder qu'un.

2024-11-14 18:59 UTC, vperron commented on api/src/alembic/versions/20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
> +               ' '||
C'est vrai que ça ne changera rien, j'ai un peu relevé par étonnement. Ne t'embete pas plus.

2024-11-14 19:00 UTC, vperron commented on api/tests/e2e/api/test_inclusion_data.py
> +        ("jeunes et personne agee", "âgée", False),
je me demande si on ne peut pas traiter ça avec un petit coup de unaccent ?

2024-11-14 19:01 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/agefiph/int_agefiph__services.sql
> +        NULL                                                         AS "profils_precisions",
Ah oui, je... j'ai eu du mal à suivre la logique :sweat:

2024-11-18 11:13 UTC, hlecuyer commented on api/tests/e2e/api/test_inclusion_data.py
> +        ("jeunes et personne agee", "âgée", False),
Mon idee, c'etait de laisser Antoine faire une premiere passe pour voir ce qu'il en pense. On va peut etre voir d'autre chose qui demanderons et c'est peut etre mieu d'attendre pour etre sur de prendre la bonne solution technique. Mais a priori, si il n'y a que les accents qui posent probleme, on peut faire ca oui.

2024-11-18 14:01 UTC, vperron commented
Je voudrai bien refaire une dernière passe ces prochains jours une fois les commits réorganisés comme suggéré !

2024-11-19 17:34 UTC, vperron reviewed
Nice, quelques petites remarques !

Je n'approuve pas encore car:
- besoin de discuter notamment sur la question des profils
- quelques petits trucs mineurs a verifier que j'ai relevé
- faut qu'on teste bien tout ça en staging

Chaud pour voir ce que donne aussi ce nouveau champ profil_precisions in situ.

2024-12-10 14:39 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
> +              values: ['regular', 'asylum', 'refugee', 'undocumented']
Bien vu, il est bien dans la doc, je le rajoute au mapping

2024-12-10 14:40 UTC, hlecuyer commented on pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
> +                - 'ukraine'
J'ai mis dans le meme ordre que la documentation. Je trouve ca plus facile a comparer si jamis ils rajoute des valeurs non ?

2024-12-10 14:42 UTC, hlecuyer commented on pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
> +            WHEN lieux.publics__accueil IN (0, 1) THEN ARRAY_APPEND(profils.profils, 'tout-publics')
Oui je crois que j'ai rate l'hebdo ou on devait en parler :(. Je me note d'en parler au daily jeudi!

2024-12-16 14:18 UTC, vmttn commented
J'ai rebased pour les migrations alembic

2025-01-07 14:04 UTC, vperron commented on api/requirements/dev-requirements.txt
> +data-inclusion-schema==0.20.0.dev1
attention à ne pas merger cela quand la PR sera validée !

2025-01-07 14:06 UTC, vperron commented on api/src/data_inclusion/api/inclusion_data/models.py
> +    # cf: 20241028_172223_c947102bb23f_add_profils_autres_field_in_service.py
attention le nom de fichier semble obsolète !

2025-01-09 11:34 UTC, vperron approved these changes
OK, j'ai mis des nitpicks ignorables je pense

2025-01-09 11:34 UTC, vperron commented on api/src/data_inclusion/api/inclusion_data/routes.py
> +               ce champs.
nit (mais ça sera public donc je préfère):
- Une recherche élargie (le é)
- sur ce champ (sans le 's' final)

Mais a le lecture je me dis surtout:
- pourquoi ne pas appeler ce query param `recherche_profil` si ça cherche dans les profils et que le doc parle de profils, pas de public ? peut etre que ca a été validé par Antoine, no sé.
- Pourquoi ne pas simplement mettre en doc: "Une recherche approfondie en texte intégral (plusieurs mots-clés combinables, non obligatoirement complets) sur les profils" ? ça me semblerait plus clair.

2025-01-09 11:34 UTC, vperron commented on api/src/data_inclusion/api/inclusion_data/routes.py
> +    ] = None,
même remarque

2025-01-09 11:34 UTC, vperron commented on deployment/MIGRATION.md
> +   ssh root@<INSTANCE_IP>
huhu merci

2025-01-09 11:34 UTC, vperron commented on deployment/MIGRATION.md
> +   ssh root@<INSTANCE_IP>
ça devrait être un autre commit cela dit, mais je chipote

2025-01-09 11:34 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/mes_aides/garage/int_mes_aides__garages__services.sql
> +        CAST(NULL AS TEXT [])                                                                       AS "justificatifs",
nit : j'aurais bien mis ces correctifs SQLFluff dans un commit à part mais j'ai pas envie de t'emmerder à ce point ^^ juste pour les prochaines fois ça vaut le coup de:
- lancer sqlfluff sur ces fichiers
- faire un commit avec juste ça
- mettre le changement sur profils_precisions ailleurs


c'est bcp plus simple pour la lecture, le revert futur, savoir où et comment a été introduit un bug... surtout sur notre base de code qui n'a pas tant de tests.

2025-01-09 11:34 UTC, vperron commented on pipeline/dbt/models/intermediate/sources/soliguide/int_soliguide__services.sql
> +            WHEN lieux.publics__accueil IN (0, 1) THEN ARRAY_APPEND(profils.profils, 'tout-publics')
donc on garde bien le tout publics pour l'instant ? je suppose que oui :)

2025-01-09 11:34 UTC, vperron commented on pipeline/dbt/models/staging/sources/soliguide/_soliguide__models.yml
> +                - 'ukraine'
oui, ok , en supposant que ils ne les changent pas eux memes hehe !

2025-01-09 13:21 UTC, hlecuyer commented
Je pense que `tout-public` sera revu lors de la revision du schema.

2025-01-09 13:29 UTC, hlecuyer commented on api/src/data_inclusion/api/inclusion_data/routes.py
> +               ce champs.
- Ca a ete valide par Antoine au vu des futur modif de schema.
- J'ai aussi fait volide le message de doc par Antoine :)

2025-01-09 14:00 UTC, merged