feat(api): add records stats for structure consultation
gip-inclusion/data-inclusion pull request #347
Opened 2024-11-21 16:42 UTC by hlecuyer

2024-11-21 19:13 UTC, vmttn requested changes
1. Sur le nommage :

* `consult` -> `view`
* `record` -> `save`

2. côté test, ça me parait suffisant. Tu pourras utiliser `pytest.mark.parametrize` sur les tests existants, au fur et à mesure que tu ajoutes des endpoints au stats.

3. il faudra prévoir une migration de données pour aligner l'historique ! On en reparle la semaine prochaine

2024-11-21 19:13 UTC, vmttn commented on api/src/data_inclusion/api/inclusion_data/services.py
> +    request: fastapi.Request,
je préfère que tu fasses ça dans `data_inclusion.api.inclusion_data.routes:retrieve_structure_endpoint`, à l'instar de ce qui est fait pour la requête chez soliguide.

la fonction `retrieve_structure` ne devrait s'occuper que de requeter la db pour récupérer un service

2024-11-21 19:22 UTC, vmttn commented on api/src/data_inclusion/api/stats_requests/models.py
> +    __tablename__ = "api__structure__stats__consultation"
```suggestion
class RetrieveStructureView(db.Base):
```

2024-11-26 10:16 UTC, hlecuyer commented on api/src/data_inclusion/api/inclusion_data/routes.py
> +    record_stats: fastapi.BackgroundTasks,
J'ai hesite... Mais oui je pense que tu as raison je vais change.

2024-11-26 10:17 UTC, hlecuyer commented on api/src/data_inclusion/api/stats_requests/structure_consultation.py
> +            structure_id=structure_id, source=source, user=username
Oui sur les autres routes

2024-11-26 10:18 UTC, hlecuyer commented on api/src/data_inclusion/api/stats_requests/structure_consultation.py
> +    except Exception as e:
Desole, c'etait du debug a la base je suis passe a travers.

2024-11-26 10:23 UTC, hlecuyer commented on api/src/data_inclusion/api/stats_requests/models.py
> +    __tablename__ = "api__structure__stats__consultation"
Du coup le nom de la table ca va surement etre `api__retrieve_structure_view`, ca te parrait ok ?
D'ailleur je n'ai pas compris d'ou venait ce mapping implicite.

Est ce qu'on ne garde pas la typo api__{structure ou service}__{nom de la route/event} ?

2024-11-26 10:24 UTC, hlecuyer commented on api/src/alembic/versions/20241121_160045_f44b9ddbecee_add_structure_consultation_stat_table.py
> +        sa.Column("source", sa.String, nullable=True),
Non effectivement

2024-11-26 11:22 UTC, hlecuyer commented on api/src/data_inclusion/api/stats_requests/structure_consultation.py
> +    except Exception as e:
Il peut y voir un interet a catch des erreurs souvent lie a des problemes de reseau ou des indispo temporaire de la base de donne et mettre des retry sur ces erreurs la. Mais a ce stade, c'est peut etre de l'overengineering...

2024-11-26 14:09 UTC, hlecuyer commented on api/src/data_inclusion/api/stats_requests/structure_consultation.py
> +    except Exception as e:
Cela dit aussi, il y en a un du cote de l'enregistrement des requests qui est logge en erreur. Est ce que sans ca on ne retouve rien cote sentry ?

2024-11-28 14:02 UTC, vperron commented on api/src/data_inclusion/api/stats_requests/structure_consultation.py
> +    except Exception as e:
Pour les erreurs de réseau, typiquement je dirais de laisser le système crasher au début pour voir si c'est un souci permanent qui ne peut pas etre résolu côté PaaS. En général, quand ça arrive c'est plutot signe qu'on se fait DDOS, ou que la DB est en train de migrer ou souffrir, pas un cas général.

Pour l'autre `except Exception`:
- je pense qu'il n'est pas _totalement_ justifié
- il devrait en effet être plus précis sur l'exception
- mais son mécanisme général est sensé : on ne veut pas que l'utilisateur se prenne une 500 si "enregistrer la requête" (ce qui est uniquement intéressant pour nous, pas pour lui) a crashé; le `logger.error` par contre va bien logger l'erreur dans Sentry, mais sans le 500 pour l'utilisateur. Ce bout de code est dans un middleware, donc sera executé quelle que soit la requete.
- ici tu es en BackgroundTask, donc ta réponse est déjà partie au moment où l'on enregistre la requête et pas de risque d'un 500 pour l'utilisateur !

2024-12-10 09:17 UTC, hlecuyer commented
@vmttn je pense avoir traiter tous les retour. J'ai fait quelques stat dans la description post migrations. si tu valide on peux tester rapidement en staging et kle passer en prod pour finir d'adapter les dashboard!

2024-12-13 11:13 UTC, vmttn approved these changes

2024-12-13 11:24 UTC, merged