feat(pipeline) : Setup deduplication as a new processings module
gip-inclusion/data-inclusion pull request #350
Opened 2024-12-10 15:27 UTC by vperron

2024-12-17 10:28 UTC, hlecuyer commented
J'ai rebase pour deployer en staging l'import des tables analytics en staging.

2024-12-17 16:00 UTC, vmttn requested changes

2024-12-17 16:00 UTC, vmttn commented on datawarehouse/processings/src/data_inclusion/processings/deduplicate.py
> +            cluster_id += 1
côté notebook on avait ça :

```python
clusters_df = pd.DataFrame(
    data=[
        {"id": record_id, "cluster_id": cluster_id, "score": score}
        for cluster_id, (records, scores) in enumerate(clustered_dupes)
        for record_id, score in zip(records, scores)
    ]
)
```

1. ça me semble ok d'expliciter `id` en `structure_id`, par contre on devrait garder `cluster_id`, car en l'état on a une colonne `id` qui n'est pas unique, c'est surprenant. Donc ça pourrait être :

```python
clusters_df = pd.DataFrame(
    data=[
        {"structure_id": record_id, "cluster_id": cluster_id, "score": score}
        for cluster_id, (records, scores) in enumerate(clustered_dupes)
        for record_id, score in zip(records, scores)
    ]
)
```

2. autre différence : tu filtres pour ne garder que les clusters avec au moins 2 éléments, ce qui me semble une bonne idée. Mais tu peux faire en une étape séparée : `clusters_df = clusters_df[clusters_df.duplicated(subset="cluster_id", keep=False)]`

donc on en serait là :

```python
clusters_df = pd.DataFrame(
    data=[
        {"structure_id": record_id, "cluster_id": cluster_id, "score": score}
        for cluster_id, (records, scores) in enumerate(clustered_dupes)
        for record_id, score in zip(records, scores)
    ]
)
# ignore cluster with single element
clusters_df = clusters_df[clusters_df.duplicated(subset="cluster_id", keep=False)]
```

3. tu calcules la taille des clusters. Je pense qu'on devrait faire ça dans un model dbt. Contrairement au calcul des doublons, ces transformations peuvent être faites en sql.

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_paires_structures.sql
> +    SELECT DISTINCT
étonné qu'on ait besoin du `DISTINCT` ici

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_structures.sql
> +
ici tu pourrais faire le calcul de la taille des groupes : `COUNT(*) OVER (PARTITION BY cluster_id) AS cluster_size`

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_clusters_par_source.sql
> +
plus simple partir de `int__doublons_structures` non ?

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_multi_source.sql
> +        CAST('{{ run_started_at.strftime("%Y-%m-%d") }}' AS DATE) AS date_day,
tu peux faire ça directement dans le snapshot 
```suggestion
```

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_mono_source.sql
> +        CAST('{{ run_started_at.strftime("%Y-%m-%d") }}' AS DATE) AS date_day,
tu peux faire ça directement dans le snapshot 
```suggestion
```

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +  - name: int__doublons_paires_structures
on ajoute un test pour garantir `structure_id_1 < structure_id_2` ? (data_tests au niveau du model)

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_mono_source.sql
ça m'a l'air plus simple en partant de `int__doublons_structures`

[exemple ici en staging](https://metabase.data.inclusion.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7Im5hdGl2ZSI6eyJxdWVyeSI6IldJVEggZG91YmxvbnMgQVMgKFNFTEVDVCBpbnRfX2RvdWJsb25zX3N0cnVjdHVyZXMuaWQgQVMgY2x1c3Rlcl9pZCwgKlxuRlJPTSBwdWJsaWNfaW50ZXJtZWRpYXRlLmludF9fZG91YmxvbnNfc3RydWN0dXJlc1xuTEVGVCBKT0lOIHB1YmxpY19pbnRlcm1lZGlhdGUuaW50X191bmlvbl9zdHJ1Y3R1cmVzX19lbmhhbmNlZCBPTiBpbnRfX2RvdWJsb25zX3N0cnVjdHVyZXMuc3RydWN0dXJlX2lkID0gaW50X191bmlvbl9zdHJ1Y3R1cmVzX19lbmhhbmNlZC5fZGlfc3Vycm9nYXRlX2lkKSxcblxuZm9vIEFTIChcbiAgICBTRUxFQ1RcbiAgICAgICAgY2x1c3Rlcl9pZCxcbiAgICAgICAgc291cmNlLFxuICAgICAgICBDT1VOVCgqKSBBUyB0b3RhbF9mcm9tX3NvdXJjZV9pbl9jbHVzdGVyXG4gICAgRlJPTSBkb3VibG9uc1xuICAgIEdST1VQIEJZIDEsIDJcbiAgICBIQVZJTkcgQ09VTlQoKikgPj0gMlxuKVxuXG5TRUxFQ1RcbiAgICBzb3VyY2UsXG4gICAgU1VNKHRvdGFsX2Zyb21fc291cmNlX2luX2NsdXN0ZXIpXG5GUk9NIGZvb1xuR1JPVVAgQlkgc291cmNlXG5PUkRFUiBCWSAyIERFU0MiLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sInR5cGUiOiJuYXRpdmUiLCJkYXRhYmFzZSI6Nn0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwidHlwZSI6InF1ZXN0aW9uIn0=)

mais curieux de voir que ça ne correspond pas aux résultats de ta version

2024-12-17 16:00 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_multi_source.sql
ici aussi ça m'a l'air plus simple en partant de int__doublons_structures

2024-12-19 14:50 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +      - name: id
yes ! ça sera plus clair.

2024-12-19 14:51 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +              min_value: 0.7
ben non, aucun... c'est même aucun en dessosu de 0.74 mais je laisse une petite marge tout de meme.

2024-12-19 14:52 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +              min_value: 0.7
je pense que c'est tout simplement corrélé au THRESHOLD de 0.75 choisi et qui doit être tout simplement utilisé en comparaison avec le score de `dedupe` en interne à la lib.

2024-12-19 14:53 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +          - not_null
yes mais attention le cluster_id est un entier.

2024-12-19 14:58 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +              min_value: 2
yes, je fais ça en réduisant un peu le range "très suspect".

2024-12-19 15:04 UTC, vperron commented on datawarehouse/processings/src/data_inclusion/processings/deduplicate.py
> +            cluster_id += 1
OK ! La seule limite que je vois à ta proposition est que l'on aura des cluster_id un peu plus "turbulents" mais je ne sais pas si ça change grand-chose. Je fais.

2024-12-20 11:56 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +              min_value: 0.7
aaaaah ok. Il faudrait qu'on finisse par regarder vraiment sous le capot :sweat_smile:

2024-12-20 11:58 UTC, vmttn commented on pipeline/dbt/models/intermediate/deduplicate/_doublons_models.yml
> +          - not_null
ah ok, mon commentaire n'était pas pertinent donc...

2025-01-06 09:22 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_mono_source.sql
En effet ma version a le souci de ne pas compter les structures en doublons "au sein d'un même cluster". Moi je compte les clusters "purement mono source" et je garde les autres comme "hybrides", c'est ça qui était compté.

Toi tu vas compter les doublons même au sein des clusters hybrides.

Par exemple si j'ai un cluster X avec 5 doublons dont 3 "france travail" et 2 "dora", ta version comptera bien les 3 "france travail" en doublon alors que ma version considèrera que c'est un cluster "non mono doublon".

2025-01-06 09:23 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_nb_mono_source.sql
Je garde ta version.

2025-01-12 16:06 UTC, vmttn approved these changes
à part un petit point, nickel :100: :100: :100: 

l'intuition que `int__doublons_nb_cross_source` et `int__doublons_nb_mono_source` pourraient être un seul et même modèle, mais ça ira très bien comme ça :+1:

2025-01-13 08:54 UTC, vperron commented on pipeline/dbt/models/intermediate/deduplicate/int__doublons_paires_structures.sql
> +
bien vu, l'info de source a en effet été ajoutée a posteriori :) Merci !

2025-01-13 09:45 UTC, merged