feat(api): add filter score_qualitee_minimum on list services and search services route
gip-inclusion/data-inclusion pull request #351
Opened 2024-12-12 13:56 UTC by hlecuyer

2024-12-13 11:23 UTC, vmttn requested changes
almost perfect :)

2024-12-13 11:23 UTC, vmttn commented on api/tests/e2e/api/test_inclusion_data.py
> +
```suggestion
```

je crois que cette partie n'ajoute rien de plus, en l'état je dirais de retirer

2024-12-13 11:23 UTC, vmttn commented on api/tests/e2e/api/test_inclusion_data.py
> +        params={"score_qualite_minimum": 0.5},
:+1: nickel d'avoir mis ce edge case

peut-être :

```suggestion
        params={"score_qualite_minimum": service_1.score_qualite},
```

pour bien voir ce que la valeur n'est pas choisie au hasard ?

2024-12-16 08:36 UTC, hlecuyer commented
@vmttn done :)

2024-12-19 17:50 UTC, merged